export const REWARDS_LOADED_ACTION = 'REWARDS_LOADED';
export const REWARDS_LOADED_NEXT_ACTION = 'REWARDS_LOADED_NEXT';
export const REWARDS_LOADING_ACTION = 'REWARDS_LOADING';
export const COLLECT_REWARD = 'COLLECT_REWARD';
